# Change these first
owner: smantriplw # Your GitHub organization or username, where this repository lives
repo: uptime-services # The name of this repository

sites:
  - name: Website
    url: https://sman3palu.sch.id
  - name: Dokumentasi/Foto Website
    url: https://dokumentasi.sman3palu.sch.id/owncloud
  - name: Verval Website
    url: https://verval.sman3palu.sch.id
  - name: ERapor K13 Website
    url: https://ek13.sman3palu.sch.id
  - name: ERapor Kelas 12 Website
    url: https://erapor12.sman3palu.sch.id
  - name: ERapor KM Website
    url: https://ekm.sman3palu.sch.id
  - name: Dapodik Portal
    url: https://dapodik.sman3palu.sch.id
  - name: SNBTX Website
    url: https://snbtx.sman3palu.sch.id
  - name: SNBP Mirror
    url: https://snbp.sman3palu.sch.id
  - name: MikroTik
    url: https://routeros.sman3palu.sch.id
  # External services
  - name: "[EXTERNAL] Telkom ASTinet Monitoring"
    url: https://telkomcare.telkom.co.id/mrtgnetcare2
  - name: "[EXTERNAL] Kemdikbud VervalPD"
    url: https://vervalpd.data.kemdikbud.go.id
  - name: "[EXTERNAL] Kemdikbud Datadik"
    url: https://datadik.kemdikbud.go.id/acc/login

assignees:
  - hansputera

i18n:
  footer: "© SMA Negeri 3 Palu 2024. All rights reserved"

commitMessages:
  commitAuthorName: "SMA Negeri 3 Palu"
  commitAuthorEmail: "operator@mail.sman3palu.sch.id"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sman3palu.sch.id
  # baseUrl: /your-repo-name
  logoUrl: https://cbt.sman3palu.sch.id/uploads/settings/logo_kanan.png
  name: SMA Negeri 3 Palu
  introTitle: "**SMA Negeri 3 Palu** adalah Sekolah Menengah Atas terakreditasi **A** yang terletak di Palu, Sulawesi Tengah, Indonesia."
  introMessage: Selamat datang di sistem daring monitoring layanan yang aktif dan digunakan di SMA Negeri 3 Palu.
  navbar:
    - title: Status
      href: /
    - title: LinkedIn
      href: https://www.linkedin.com/school/smantigapalu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
